### ISSUE TITLE
老哥，这个现在是什么状态呀

### ISSUE THREAD

**Issue by CoinCheung** [coolcooldool/tencent-weibo-exporter#4]
你好呀，知乎过来的，这个现在能正常备份吗，看read me说会自动注销帐号?

**Comment by f-is-h** [comment]
Readme并没有说是因为这个程序会注销账号。。。完全没有一点关系！
是腾讯不什么为什么把我的账号注销了。

由于我的账号被注销了，所以我没有办法调试程序，所以也不知道可不可以正常使用，但有人反应貌似不太稳定。

**Comment by CoinCheung** [comment]
好的，然后linux下怎么使用登录版呀，貌似文档里面没说怎么用，只说了下载geckodriver然后放到windows的c盘里面，并没说怎么启动脚本啥的?

**Comment by f-is-h** [comment]
打开浏览器后扫码登录应该就可以了。具体程序运行环境的配置建议找个会点Python的朋友帮下忙应该比较好。

**Comment by CoinCheung** [comment]
我用的 anaconda  默认的  python3.7, geckodriver放到  anaconda的目录下面了，没自己建环境，就用的自带的python3.7，然后我运行 logversion6，报了这个错 ：
···
开始登录腾讯微博...
登录超时...
打开我的广播超时...
开始分析腾讯微博第　1 页...
Traceback (most recent call last):
  File "tencent_weibo.py", line 154, in <module>
    weibo.start()
  File "tencent_weibo.py", line 136, in start
    self.get_stories()
  File "tencent_weibo.py", line 74, in get_stories
    talk_list = self.browser.find_element_by_id('talkList')
  File "D:\Users\hp\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "D:\Users\hp\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "D:\Users\hp\Anaconda3\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "D:\Users\hp\Anaconda3\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: [id="talkList"]
···
这个是什么原因呢

**Comment by f-is-h** [comment]
Readme里已经写了，我目前没有办法调试这个程序的。你自己调试一下吧。
